# Generated by Django 2.0.6 on 2018-10-26 01:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='emergency_fund',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='sign_up_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='account',
            name='user_name',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='account',
            name='user_pass',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='activity',
            name='emergency_deposit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='emergency_deposit_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='emergency_widthdrawl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='emergency_widthdrawl_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='deposit_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='widthdrawl_date',
            field=models.DateTimeField(null=True),
        ),
    ]
