# Generated by Django 2.0.6 on 2018-10-26 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_account_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user_pass',
        ),
    ]
