# Generated by Django 2.0.6 on 2018-10-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_auto_20181026_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='deposit',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='deposit_date',
            new_name='transaction_date',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='emergency_deposit',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='emergency_deposit_date',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='emergency_widthdrawl',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='emergency_widthdrawl_date',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='widthdrawl',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='widthdrawl_date',
        ),
        migrations.AddField(
            model_name='activity',
            name='account_type',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='activity',
            name='widthdrawlorDeposit',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
