# Generated by Django 2.0.6 on 2018-10-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_activity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='account',
            name='emergency_fund',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='activity',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
